[package]
name = "quack_os"
version = "0.1.0"
edition = "2018"
authors = ["Yaman Qassas <yaman102011@gmail.com>"]

[dependencies]
bootloader = "0.9.8"
volatile = "0.2.6"
spin = "0.5.2"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]